### ISSUE TITLE
consider moving trust_atom_types into coordination

### ISSUE THREAD

**Issue by dauphin3** [trustgraph/trustgraph-holochain#65]
does TA types need to be a separate zome or would it make more sense to have it as a module in coordination?

**Comment by harlantwood** [comment]
> does TA types need to be a separate zome or would it make more sense to have it as a module in coordination?

It does have to be separate.  When we include TA in eg Mews dna, we get an error bc multiple entries if we bring in TA integrity or coord zome.  

Splitting types into their own zomes is a common HC pattern in reusable library zomes, for this very reason.
